### ISSUE TITLE
Not working with 1.1

### ISSUE THREAD

**Issue by TIle7** [notfood/RimWorld-ResearchPal#16]
You asked for log in Steam discussions. 
So, not working at all. Actually, when in mod list, half of the main buttons dissapear.

Could not find a type named ResearchPal.MainButtonWorker_ResearchTree
Verse.Log:Error(String, Boolean)
Verse.ParseHelper:ParseType(String)
Verse.ParseHelper:FromString(String)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlLoader:DMD<DMD<DefFromNode_Patch2>?356971776::DefFromNode_Patch2>(XmlNode, LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

Could not find a type named ResearchPal.MainTabWindow_ResearchTree
Verse.Log:Error(String, Boolean)
Verse.ParseHelper:ParseType(String)
Verse.ParseHelper:FromString(String)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXml(XmlNode, Boolean)
Verse.DirectXmlToObject:ObjectFromXmlReflection(XmlNode, Boolean)
Verse.DirectXmlLoader:DMD<DMD<DefFromNode_Patch2>?356971776::DefFromNode_Patch2>(XmlNode, LoadableXmlAsset)
Verse.LoadedModManager:ParseAndProcessXML(XmlDocument, Dictionary`2)
Verse.LoadedModManager:LoadAllActiveMods()
Verse.PlayDataLoader:DoPlayLoad()
Verse.PlayDataLoader:LoadAllPlayData(Boolean)
Verse.<>c:<Start>b__6_1()
Verse.LongEventHandler:RunEventFromAnotherThread(Action)
Verse.<>c:<UpdateCurrentAsynchronousEvent>b__27_0()
System.Threading.ThreadHelper:ThreadStart_Context(Object)
System.Threading.ExecutionContext:RunInternal(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object, Boolean)
System.Threading.ExecutionContext:Run(ExecutionContext, ContextCallback, Object)
System.Threading.ThreadHelper:ThreadStart()

**Comment by notfood** [comment]
That looks like something worse happened. The DLL not loading or something. Post the full thing as attachment.

**Comment by TIle7** [comment]
https://gist.github.com/4c60799910caa02d43de2c58a0ee1548

**Comment by notfood** [comment]
You're using both ResearchTree and ResearchPal at the same time. Of course it breaks, they use the same MainButtonDef.
```
Research Tree(fluffy.researchtree): ResearchTree(av:3.0.0,fv:3.17.533)
ResearchPal(notfood.ResearchPal): 0MultiplayerAPI(av:0.1.0,fv:0.1.0), ResearchTree(av:3.0.0,fv:3.13.503)
```

**Comment by TIle7** [comment]
Shit. Sorry I understood that pal was like an addon.
Sorry.
